
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git checkout -b pages
    - run: yarn install
    - run: pwd
    - run: ls -a
    - run: yarn build
    - run: mv .gitignore unusedgitignore
    - run: mv .gitignorepages .gitignore
    - run: git status
    - run: git add docs/
    - run: git status
    - run: git push -u origin pages --force

