
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git checkout -b pages
    - run: yarn install
    - run: pwd
    - run: ls -a
    - run: yarn build
    - run: git status
    - name: Simple commit
      # You may pin to the exact commit or the version.
      # uses: zwaldowski/git-commit-action@66730766679672410dc04830ae6389f4376c8c94
      uses: zwaldowski/git-commit-action@v1
    - run: git status
    - run: git push
